#!/usr/bin/env python3
"""Build a paper-style PathMNIST post-hoc env manifest from Slurm logs."""

from __future__ import annotations

import argparse
import re
import shlex
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Candidate:
    method: str
    seed: int
    checkpoint_best: Path
    checkpoint_last: Path
    output_dir: Path
    log_mtime: float


def command_from_stdout(path: Path) -> str | None:
    if not path.is_file():
        return None
    for line in path.read_text(errors="replace").splitlines():
        if line.startswith("Command: "):
            return line.removeprefix("Command: ").strip()
    return None


def output_dir_from_stderr(path: Path) -> Path | None:
    if not path.is_file():
        return None
    text = path.read_text(errors="replace")
    if "Tests took" not in text:
        return None
    matches = re.findall(r"Output directory is ([^.]+)\.", text)
    if not matches:
        return None
    return Path(matches[-1])


def parse_method_and_seed(command: str) -> tuple[str | None, int | None]:
    parts = shlex.split(command)
    if "--method-name" not in parts:
        return None, None
    method = parts[parts.index("--method-name") + 1]
    if method == "het-xl" and "--use-het" in parts:
        method = "het"
    seed = 42
    if "--seed" in parts:
        seed = int(parts[parts.index("--seed") + 1])
    return method, seed


def collect_candidates(repo_root: Path) -> list[Candidate]:
    rows: list[Candidate] = []
    slurm_dir = repo_root / "logs" / "slurm"
    for stdout in sorted(slurm_dir.glob("pathmnist-*.out")):
        stderr = stdout.with_suffix(".err")
        command = command_from_stdout(stdout)
        output_dir = output_dir_from_stderr(stderr)
        if command is None or output_dir is None:
            continue
        method, seed = parse_method_and_seed(command)
        if method is None or seed is None:
            continue
        full_output_dir = repo_root / output_dir
        checkpoint_best = full_output_dir / "checkpoint_best.pt"
        checkpoint_last = full_output_dir / "checkpoint_last.pt"
        if not checkpoint_best.is_file():
            continue
        rows.append(
            Candidate(
                method=method,
                seed=seed,
                checkpoint_best=checkpoint_best,
                checkpoint_last=checkpoint_last,
                output_dir=full_output_dir,
                log_mtime=max(stdout.stat().st_mtime, stderr.stat().st_mtime),
            )
        )
    return rows


def choose_latest(candidates: list[Candidate], method: str, seed: int) -> Candidate | None:
    matching = [
        candidate
        for candidate in candidates
        if candidate.method == method and candidate.seed == seed
    ]
    if not matching:
        return None
    return max(matching, key=lambda candidate: candidate.log_mtime)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--ce-seeds", type=int, nargs="*", default=(42, 43, 44, 45, 46))
    parser.add_argument("--sngp-seed", type=int, default=42)
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    candidates = collect_candidates(repo_root)

    ce_members = []
    missing = []
    for seed in args.ce_seeds:
        candidate = choose_latest(candidates, "ce-baseline", seed)
        if candidate is None:
            missing.append(f"ce-baseline seed {seed}")
        else:
            if not candidate.checkpoint_last.is_file():
                missing.append(f"ce-baseline seed {seed} checkpoint_last.pt")
            ce_members.append(candidate)

    sngp = choose_latest(candidates, "sngp", args.sngp_seed)
    if sngp is None:
        missing.append(f"sngp seed {args.sngp_seed}")

    if missing:
        details = "\n".join(f"- {item}" for item in missing)
        raise SystemExit(f"Missing required post-hoc checkpoints:\n{details}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    best_paths = ",".join(str(candidate.checkpoint_best) for candidate in ce_members)
    last_paths = ",".join(str(candidate.checkpoint_last) for candidate in ce_members)
    with args.output.open("w") as handle:
        handle.write("# Generated by tools/hpc/build_pathmnist_posthoc_env_manifest.py\n")
        handle.write(f"PATHMNIST_BEST_WEIGHT_PATHS={best_paths}\n")
        handle.write(f"PATHMNIST_LAST_WEIGHT_PATHS={last_paths}\n")
        handle.write(f"PATHMNIST_SNGP_BEST_WEIGHT_PATH={sngp.checkpoint_best}\n")

    print(f"Wrote post-hoc manifest to {args.output}")
    print("CE members:")
    for candidate in ce_members:
        print(f"- seed {candidate.seed}: {candidate.output_dir}")
    print(f"SNGP seed {args.sngp_seed}: {sngp.output_dir}")


if __name__ == "__main__":
    main()
