#!/usr/bin/env bash
# Wait for fresh PathMNIST CE/SNGP checkpoints, then submit paper-style post-hoc jobs.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

BASE_JOB_ID="${BASE_JOB_ID:?set BASE_JOB_ID to the fresh PathMNIST base array job id}"
RUN_ID="${RUN_ID:-$(date +%Y%m%d-%H%M%S)-pathmnist-posthoc-paperstyle}"
SBATCH_BIN="${SBATCH_BIN:-sbatch.tinygpu}"
SLURM_PARTITION="${SLURM_PARTITION:-a100}"
SLURM_GRES="${SLURM_GRES:-gpu:a100:1}"
ENV_SETUP="${ENV_SETUP:-$REPO_ROOT/hpc_env.sh}"
DATA_ROOT="${DATA_ROOT:?set DATA_ROOT to the dataset root}"
PYTHON_BIN="${PYTHON_BIN:-python}"

COMMAND_DIR="$REPO_ROOT/logs/pathmnist_hpc_${RUN_ID}"
MANIFEST="$REPO_ROOT/configs/pathmnist_posthoc_weight_paths_${RUN_ID}.env"
CMD_FILE="$COMMAND_DIR/commands.txt"
STATUS_FILE="$COMMAND_DIR/status.log"

mkdir -p "$COMMAND_DIR" "$REPO_ROOT/configs" "$REPO_ROOT/logs/slurm"

log() {
  echo "[$(date --iso-8601=seconds)] $*" | tee -a "$STATUS_FILE"
}

wait_for_base_job() {
  log "Waiting for base job ${BASE_JOB_ID} to leave the TinyGPU queue."
  while squeue.tinygpu -h -j "$BASE_JOB_ID" | grep -q .; do
    sleep 300
  done
  log "Base job ${BASE_JOB_ID} is no longer queued."
}

extract_output_dir() {
  local task_id="$1"
  local err_file="$REPO_ROOT/logs/slurm/pathmnist-train_${BASE_JOB_ID}_${task_id}.err"
  if [[ ! -f "$err_file" ]]; then
    log "Missing Slurm stderr for task ${task_id}: ${err_file}"
    return 1
  fi
  if ! grep -q "Tests took" "$err_file"; then
    log "Task ${task_id} does not show completed final tests in ${err_file}"
    return 1
  fi
  local output_dir
  output_dir="$(grep "Output directory is" "$err_file" | tail -1 | sed -E 's/.*Output directory is ([^.]*)\\..*/\\1/')"
  if [[ -z "$output_dir" || ! -d "$REPO_ROOT/$output_dir" ]]; then
    log "Could not resolve output directory for task ${task_id}"
    return 1
  fi
  printf '%s\n' "$REPO_ROOT/$output_dir"
}

build_manifest() {
  # Base array command order:
  # 1 CE baseline seed 42, 2 SNGP seed 42, 3-6 CE baseline seeds 43-46.
  local ce_dirs=()
  local task
  for task in 1 3 4 5 6; do
    ce_dirs+=("$(extract_output_dir "$task")")
  done
  local sngp_dir
  sngp_dir="$(extract_output_dir 2)"

  local best_paths=""
  local last_paths=""
  local sep=""
  local dir
  for dir in "${ce_dirs[@]}"; do
    for ckpt in "$dir/checkpoint_best.pt" "$dir/checkpoint_last.pt"; do
      if [[ ! -f "$ckpt" ]]; then
        log "Missing checkpoint: ${ckpt}"
        return 1
      fi
    done
    best_paths+="${sep}$dir/checkpoint_best.pt"
    last_paths+="${sep}$dir/checkpoint_last.pt"
    sep=","
  done

  if [[ ! -f "$sngp_dir/checkpoint_best.pt" ]]; then
    log "Missing SNGP checkpoint: ${sngp_dir}/checkpoint_best.pt"
    return 1
  fi

  cat > "$MANIFEST" <<EOF_MANIFEST
# Generated by tools/hpc/watch_and_submit_pathmnist_posthoc_paperstyle.sh
PATHMNIST_BEST_WEIGHT_PATHS=$best_paths
PATHMNIST_LAST_WEIGHT_PATHS=$last_paths
PATHMNIST_SNGP_BEST_WEIGHT_PATH=$sngp_dir/checkpoint_best.pt
EOF_MANIFEST
  log "Wrote manifest ${MANIFEST}"
}

common_args() {
  printf '%q ' \
    "$PYTHON_BIN" train.py \
    --dataset hard/pathmnist \
    --dataset-id hard/pathmnist \
    --data-dir "$DATA_ROOT/pathmnist_cache/pathmnist" \
    --data-dir-id "$DATA_ROOT/pathmnist_cache/pathmnist" \
    --dataset-download \
    --model-name timm/resnet_50 \
    --num-classes 9 \
    --opt adamw \
    --weight-decay 2e-5 \
    --lr-base 0.001 \
    --batch-size 128 \
    --accumulation-steps 16 \
    --epochs 0 \
    --seed 42 \
    --img-size 224 \
    --mean 0.485,0.456,0.406 \
    --std 0.229,0.224,0.225 \
    --train-subset 1.0 \
    --evaluate-on-test-sets \
    --storage-device cpu \
    --num-workers 8 \
    --num-eval-workers 8 \
    --loss cross-entropy \
    --discard-ood-test-sets \
    --pin-memory
}

write_eval_command() {
  local method="$1"
  local weights="$2"
  shift 2
  {
    common_args
    printf '%q ' --method-name "$method" --weight-paths "$weights" "$@"
    printf '\n'
  } >> "$CMD_FILE"
}

write_swag_command() {
  local weight="$1"
  {
    printf '%q ' \
      "$PYTHON_BIN" train.py \
      --dataset hard/pathmnist \
      --dataset-id hard/pathmnist \
      --data-dir "$DATA_ROOT/pathmnist_cache/pathmnist" \
      --data-dir-id "$DATA_ROOT/pathmnist_cache/pathmnist" \
      --dataset-download \
      --model-name timm/resnet_50 \
      --num-classes 9 \
      --opt momentum \
      --momentum 0.9 \
      --weight-decay 0.0001 \
      --lr 0.01 \
      --sched-kwargs sched=none \
      --batch-size 128 \
      --accumulation-steps 1 \
      --epochs 40 \
      --seed 42 \
      --img-size 224 \
      --mean 0.485,0.456,0.406 \
      --std 0.229,0.224,0.225 \
      --train-subset 1.0 \
      --evaluate-on-test-sets \
      --storage-device cpu \
      --num-workers 8 \
      --num-eval-workers 8 \
      --loss cross-entropy \
      --method-name swag \
      --use-low-rank-cov \
      --max-rank 20 \
      --num-checkpoints-per-epoch 1 \
      --num-mc-samples 30 \
      --weight-paths "$weight" \
      --discard-ood-test-sets \
      --pin-memory
    printf '\n'
  } >> "$CMD_FILE"
}

write_commands() {
  # shellcheck disable=SC1090
  source "$MANIFEST"
  : > "$CMD_FILE"

  write_eval_command deep-ensemble "$PATHMNIST_BEST_WEIGHT_PATHS" \
    --eval-metric id_eval_one_minus_max_probs_of_bma_auroc_hard_bma_correctness_original

  IFS=',' read -r -a best_array <<< "$PATHMNIST_BEST_WEIGHT_PATHS"
  IFS=',' read -r -a last_array <<< "$PATHMNIST_LAST_WEIGHT_PATHS"

  local weight
  for weight in "${best_array[@]}"; do
    write_eval_command temperature-scaling "$weight" \
      --eval-metric id_eval_one_minus_max_probs_of_bma_auroc_hard_bma_correctness_original \
      --use-temperature-scaling
  done

  for weight in "${last_array[@]}"; do
    write_eval_command mahalanobis "$weight" \
      --eval-metric id_eval_mahalanobis_values_auroc_hard_bma_correctness_original \
      --magnitude 0.001
  done

  write_eval_command ddu "$PATHMNIST_SNGP_BEST_WEIGHT_PATH" \
    --eval-metric id_eval_one_minus_max_probs_of_bma_auroc_hard_bma_correctness_original \
    --use-spectral-normalization \
    --spectral-normalization-iteration 1 \
    --spectral-normalization-bound 6 \
    --use-spectral-normalized-batch-norm

  for weight in "${best_array[@]}"; do
    write_eval_command laplace "$weight" \
      --eval-metric id_eval_one_minus_max_probs_of_bma_auroc_hard_bma_correctness_original \
      --hessian-structure kron \
      --num-mc-samples 1000 \
      --num-mc-samples-cv 1000 \
      --pred-type glm
  done

  for weight in "${last_array[@]}"; do
    write_swag_command "$weight"
  done

  log "Wrote $(wc -l < "$CMD_FILE") posthoc commands to ${CMD_FILE}"
}

submit_posthoc() {
  local num_tasks
  num_tasks="$(wc -l < "$CMD_FILE")"
  log "Submitting ${num_tasks} PathMNIST paper-style posthoc tasks."
  "$SBATCH_BIN" \
    --job-name pathmnist-posthoc \
    --array "1-${num_tasks}" \
    --gres "$SLURM_GRES" \
    --time 24:00:00 \
    --partition "$SLURM_PARTITION" \
    --export "ALL,CMD_FILE=${CMD_FILE},WORK_DIR=${REPO_ROOT},ENV_SETUP=${ENV_SETUP}" \
    tools/hpc/untangle_job_array.sbatch | tee -a "$STATUS_FILE"
}

wait_for_base_job
build_manifest
write_commands
submit_posthoc
log "PathMNIST posthoc watcher finished."
