#!/usr/bin/env python3
"""Create the CIFAR-10 posthoc checkpoint manifest from checkpoint directories."""

from __future__ import annotations

import argparse
from pathlib import Path


def checkpoint_dirs(root: Path) -> list[Path]:
    return sorted(
        [
            path
            for path in root.iterdir()
            if path.is_dir()
            and (path / "checkpoint_best.pt").is_file()
            and (path / "checkpoint_last.pt").is_file()
        ],
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "dirs",
        nargs="*",
        type=Path,
        help="Five checkpoint directories. If omitted, use the latest five under --root.",
    )
    parser.add_argument("--root", type=Path, default=Path("checkpoints"))
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("configs/cifar10_posthoc_weight_paths.env"),
    )
    args = parser.parse_args()

    dirs = args.dirs or checkpoint_dirs(args.root)[:5]
    if len(dirs) != 5:
        raise SystemExit(
            f"Expected exactly five checkpoint directories, found {len(dirs)}."
        )

    missing = [
        path
        for directory in dirs
        for path in (directory / "checkpoint_best.pt", directory / "checkpoint_last.pt")
        if not path.is_file()
    ]
    if missing:
        raise SystemExit("Missing checkpoint files:\n" + "\n".join(map(str, missing)))

    best_paths = ",".join(str(path / "checkpoint_best.pt") for path in dirs)
    last_paths = ",".join(str(path / "checkpoint_last.pt") for path in dirs)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        "# Generated by tools/make_cifar10_posthoc_manifest.py\n"
        f"CIFAR10_BEST_WEIGHT_PATHS={best_paths}\n"
        f"CIFAR10_LAST_WEIGHT_PATHS={last_paths}\n"
    )
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
