#!/usr/bin/env bash
# Resume MHIST post-hoc evaluation from already trained CE members.
set -u

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || exit 1

SOURCE_RUN_ID="${SOURCE_RUN_ID:-20260625-113116-mhist-posthoc}"
RUN_ID="${RUN_ID:-$(date +%Y%m%d-%H%M%S)-mhist-posthoc-resume}"
SOURCE_LOG_DIR="$REPO_ROOT/logs/mhist_posthoc_${SOURCE_RUN_ID}"
LOG_DIR="$REPO_ROOT/logs/mhist_posthoc_${RUN_ID}"
STATUS_FILE="$LOG_DIR/status.tsv"
FAILED_FILE="$LOG_DIR/failed.tsv"
PYTHON_BIN="${PYTHON_BIN:-python3}"
DATA_DIR="${MHIST_DATA_DIR:-./data/MHIST}"
SOFT_LABEL_ROOT="${MHIST_SOFT_LABEL_ROOT:-./data/MHIST}"
STORAGE_DEVICE="${STORAGE_DEVICE:-cpu}"
SEEDS=(${SEEDS:-0 1 2 3 4})

mkdir -p "$LOG_DIR" configs
printf 'run_id\tphase\tstage\tstatus\texit_code\tstarted_at\tfinished_at\tlog\n' > "$STATUS_FILE"
: > "$FAILED_FILE"

record_status() {
  local phase="$1" stage="$2" status="$3" rc="$4" started="$5" finished="$6" log="$7"
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$RUN_ID" "$phase" "$stage" "$status" "$rc" "$started" "$finished" "$log" \
    >> "$STATUS_FILE"
}

extract_output_dir() {
  local log_file="$1"
  sed -n 's/.*Output directory is \(checkpoints\/[^.]*\).*/\1/p' "$log_file" | tail -1
}

make_manifest() {
  local phase="$1"
  local manifest="$REPO_ROOT/configs/mhist_posthoc_weight_paths_${RUN_ID}_${phase}.env"
  local best_paths=() last_paths=() log_file output_dir

  for seed in "${SEEDS[@]}"; do
    log_file="$SOURCE_LOG_DIR/${phase}_ce_seed${seed}.log"
    output_dir="$(extract_output_dir "$log_file")"
    if [[ -z "$output_dir" || ! -f "$output_dir/checkpoint_best.pt" || ! -f "$output_dir/checkpoint_last.pt" ]]; then
      echo "Missing CE checkpoints for ${phase}, seed ${seed}. Source log: ${log_file}" >&2
      return 1
    fi
    best_paths+=("$output_dir/checkpoint_best.pt")
    last_paths+=("$output_dir/checkpoint_last.pt")
  done

  local best_joined last_joined
  best_joined="$(IFS=,; echo "${best_paths[*]}")"
  last_joined="$(IFS=,; echo "${last_paths[*]}")"

  {
    echo "# Generated by tools/resume_mhist_posthoc_from_ce_members.sh"
    echo "# Source CE run: ${SOURCE_RUN_ID}"
    echo "MHIST_BEST_WEIGHT_PATHS=${best_joined}"
    echo "MHIST_LAST_WEIGHT_PATHS=${last_joined}"
  } > "$manifest"
  echo "$manifest"
}

run_posthoc() {
  local phase="$1" subset="$2" method="$3" manifest="$4"
  local log_file="$LOG_DIR/${phase}_${method}.log"
  local started finished rc

  set -a
  source "$manifest"
  set +a

  local common_args=(
    --accumulation-steps 1
    --batch-size 128
    --crop-pct 1
    --data-dir "$DATA_DIR"
    --soft-label-root "$SOFT_LABEL_ROOT"
    --dataset hard/mhist
    --dataset-id soft/mhist
    --discard-ood-test-sets
    --evaluate-on-test-sets
    --hflip 0.5
    --img-size 32
    --loss cross-entropy
    --mean 0.4914,0.4822,0.4465
    --model-name untangle/wide_resnet_c_preact_26_10
    --momentum 0.9
    --num-classes 2
    --padding 2
    --pin-memory
    --seed 42
    --std 0.2023,0.1994,0.2010
    --storage-device "$STORAGE_DEVICE"
    --train-subset "$subset"
  )

  started="$(date --iso-8601=seconds)"
  echo "[$started] START ${phase} ${method}"

  case "$method" in
    deep-ensemble)
      "$PYTHON_BIN" train.py "${common_args[@]}" \
        --epochs 0 \
        --eval-metric id_eval_one_minus_max_probs_of_bma_auroc_hard_bma_correctness_original \
        --lr 0 \
        --method-name deep-ensemble \
        --opt nesterov \
        --sched-kwargs 'sched=none' \
        --weight-decay 0 \
        --weight-paths "$MHIST_BEST_WEIGHT_PATHS" > "$log_file" 2>&1
      ;;
    temperature-scaling)
      "$PYTHON_BIN" train.py "${common_args[@]}" \
        --epochs 0 \
        --eval-metric id_eval_one_minus_max_probs_of_bma_auroc_hard_bma_correctness_original \
        --lr 0 \
        --method-name temperature-scaling \
        --opt nesterov \
        --sched-kwargs 'sched=none' \
        --use-temperature-scaling \
        --weight-decay 0 \
        --weight-paths "$MHIST_BEST_WEIGHT_PATHS" > "$log_file" 2>&1
      ;;
    swag)
      "$PYTHON_BIN" train.py "${common_args[@]}" \
        --epochs 40 \
        --eval-metric id_eval_one_minus_max_probs_of_bma_auroc_hard_bma_correctness_original \
        --lr 0.01 \
        --max-rank 20 \
        --method-name swag \
        --num-checkpoints-per-epoch 1 \
        --num-mc-samples 30 \
        --opt momentum \
        --sched-kwargs 'sched=none' \
        --use-low-rank-cov \
        --weight-decay 0.0001 \
        --weight-paths "$MHIST_LAST_WEIGHT_PATHS" > "$log_file" 2>&1
      ;;
    *)
      echo "Unknown post-hoc method: $method" > "$log_file"
      rc=2
      ;;
  esac
  rc="${rc:-$?}"
  finished="$(date --iso-8601=seconds)"

  if [[ $rc -eq 0 ]]; then
    record_status "$phase" "$method" done 0 "$started" "$finished" "$log_file"
    echo "[$finished] DONE ${phase} ${method}"
  else
    record_status "$phase" "$method" failed "$rc" "$started" "$finished" "$log_file"
    printf '%s\t%s\t%s\n' "$phase" "$method" "$log_file" >> "$FAILED_FILE"
    echo "[$finished] FAIL ${phase} ${method} exit=${rc}"
  fi
}

run_phase() {
  local phase="$1" subset="$2"
  local manifest started finished

  echo "[$(date --iso-8601=seconds)] PHASE START ${phase} subset=${subset}"
  started="$(date --iso-8601=seconds)"
  if manifest="$(make_manifest "$phase")"; then
    finished="$(date --iso-8601=seconds)"
    record_status "$phase" manifest done 0 "$started" "$finished" "$manifest"
  else
    finished="$(date --iso-8601=seconds)"
    record_status "$phase" manifest failed 1 "$started" "$finished" ""
    return 1
  fi

  run_posthoc "$phase" "$subset" deep-ensemble "$manifest"
  run_posthoc "$phase" "$subset" temperature-scaling "$manifest"
  run_posthoc "$phase" "$subset" swag "$manifest"

  started="$(date --iso-8601=seconds)"
  record_status "$phase" mahalanobis blocked 0 "$started" "$started" \
    "No validated MHIST OOD loader is available for logistic-regressor fitting."
  record_status "$phase" laplace blocked 0 "$started" "$started" \
    "The installed Laplace stack is missing curvlinops._base."
  echo "[$(date --iso-8601=seconds)] PHASE END ${phase}"
}

echo "[$(date --iso-8601=seconds)] MHIST post-hoc resume ${RUN_ID}"
echo "Source CE run: ${SOURCE_RUN_ID}"
echo "Methods: Deep Ensemble, Temperature Scaling, SWAG"
echo "Blocked: Mahalanobis (no OOD fitting set), Laplace (missing dependency)"

run_phase full-data 1.0
run_phase scarce-50pct 0.5
run_phase scarce-10pct 0.1

echo "[$(date --iso-8601=seconds)] Resume queue finished."
